"""adding seat counts and status to reservation

Revision ID: feca89220bb9
Revises: 9f37f3853a16
Create Date: 2025-07-15 21:53:17.369727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'feca89220bb9'
down_revision: Union[str, Sequence[str], None] = '9f37f3853a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_seater', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('four_seater', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'cancelled', 'completed', name='bookingstatus'), nullable=False, server_default="active"))
        batch_op.create_index(batch_op.f('ix_reservation_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_booking_time'), ['booking_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_booking_time'))
        batch_op.drop_index(batch_op.f('ix_reservation_booking_date'))
        batch_op.drop_column('status')
        batch_op.drop_column('four_seater')
        batch_op.drop_column('two_seater')

    # ### end Alembic commands ###
